name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install flask

    - name: Run Flask App
      run: |
        python app.py &
        sleep 10

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=srushti-ravindra_devsecops-project
          -Dsonar.organization=srushti-ravindra
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=.

    - name: Run OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://127.0.0.1:5000'